name: push to swarm

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo

      - name: Upload
        id: swarm-upload
        uses: ethersphere/swarm-actions/upload-dir@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          dir: ./public
          index-document: index.html

      - name: update feed
        id: swarm-feed
        uses: ethersphere/swarm-actions/write-feed@latest
        with:
          bee-url: https://gateway.fairdatasociety.org/proxy/
          reference: ${{ steps.swarm-upload.outputs.reference }}
          topic: index
          signer: ${{ secrets.SIGNER }}
          
      - name: convert feed reference to cid
        id: swarm-cid
        uses: ethersphere/swarm-actions/reference-to-cid@latest
        with:
          reference: ${{ steps.swarm-feed.outputs.manifest }}

      - name: Result information
        run: |
          echo "upload ref: " ${{ steps.swarm-upload.outputs.reference }}
          echo "feed ref: " ${{ steps.swarm-feed.outputs.reference }}
          echo "CID: " ${{ steps.swarm-cid.outputs.cid }}
          echo "Feed Manifest: " ${{ steps.swarm-feed.outputs.manifest }}
          echo "Site URL: " https://${{ steps.swarm-cid.outputs.cid }}.bzz.link/
